controller_manager:
  ros__parameters:
    update_rate: 100 # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    joint_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    joint_position_controller:
      type: joint_position_controller/JointPositionController

camera_controller:
  ros__parameters:
    joints:
      - wheel_FR_joint
      - wheel_FL_joint
      - wheel_RR_joint
      - wheel_RL_joint
    move_robot:
      type: move_robot/MoveRobot



joint_trajectory_controller:
  ros__parameters:
    joints:
      # - joint1
      # - joint2
      # - joint3
      - wheel_FR_joint
      - wheel_FL_joint
      - wheel_RR_joint
      - wheel_RL_joint

    write_op_modes:
      # - joint1
      # - joint2
      # - joint3
      - wheel_FR_joint
      - wheel_FL_joint
      - wheel_RR_joint
      - wheel_RL_joint
      
    
    interface_name: position

    command_interfaces:
      - position
    
    state_interfaces:
      - position
      - velocity

    state_publish_rate: 50.0 # Defaults to 50
    action_monitor_rate: 20.0 # Defaults to 20

    allow_partial_joints_goal: false # Defaults to false
    hardware_state_has_offset: true
    deduce_states_from_derivatives: true
    
    constraints:
      stopped_velocity_tolerance: 0.01 # Defaults to 0.01
      goal_time: 0.0 # Defaults to 0.0 (start immediately)

joint_position_controller:
  ros__parameters:
    joints:
      # - joint1
      # - joint2
      # - joint3
      - wheel_FR_joint
      - wheel_FL_joint
      - wheel_RR_joint
      - wheel_RL_joint
      

    write_op_modes:
      # - joint1
      # - joint2
      # - joint3
      - wheel_FR_joint
      - wheel_FL_joint
      - wheel_RR_joint
      - wheel_RL_joint
      
    
    interface_name: position

    command_interfaces:
      - position
    
    state_interfaces:
      - position
      - velocity

    state_publish_rate: 50.0 # Defaults to 50
    action_monitor_rate: 20.0 # Defaults to 20

    allow_partial_joints_goal: false # Defaults to false
    hardware_state_has_offset: true
    deduce_states_from_derivatives: true
    
    constraints:
      stopped_velocity_tolerance: 0.01 # Defaults to 0.01
      goal_time: 0.0 # Defaults to 0.0 (start immediately)
    